### ISSUE TITLE
RVIZ - Transformed Point Cloud tf issue #1

### ISSUE THREAD

**Issue by SIlvaMFPedro** [lardemua/ros_bridge#1]
@miguelriemoliveira can you help me please?
I created a ROS package(carla_ros_pcl_filter) that filters the point clouds from the lidar sensors of the vehicle. Basically what i did was create a subscriber that collects the PointCloud2 message from the lidar, convert the PointCloud2 cloud to the PCL format, apply the filtering method, convert back from PCL to the PointCloud2 format and publish the message in a new topic. But when i want to visualize the cloud in RVIZ it says it does not have any /tf associated with that point cloud. 
![Screenshot from 2019-05-16 21-15-44](https://user-images.githubusercontent.com/22821533/57884290-38476380-7820-11e9-8c21-19ea169d2212.png)
Do i need to include a static point transform when i publish the ROS message?
When i do rostopic echo /carla/ego_vehicle/lidar/lidar1/new_point_cloud it works fine.
![Screenshot from 2019-05-16 21-17-14](https://user-images.githubusercontent.com/22821533/57884321-44cbbc00-7820-11e9-8486-c73fb7820f09.png)
How can i solve this issue?

Thanks.

Pedro Silva

**Comment by SIlvaMFPedro** [comment]
Fixed the issue. I just had to add the frame ID to the header of the new cloud message.
All that is left is to correct the cloud filtering algorithm.
![Screenshot from 2019-05-18 16-52-18](https://user-images.githubusercontent.com/22821533/57972407-d0b12580-7991-11e9-9008-8c42e48f9009.png)

**Comment by miguelriemoliveira** [comment]
Great! Congratulations. Sorry for not answering sooner but had not time to take a look

**Comment by miguelriemoliveira** [comment]
The pictures look very nice.
