### ISSUE TITLE
ROS & PCL - Cloud Filtering Algorithms issue #2

### ISSUE THREAD

**Issue by SIlvaMFPedro** [lardemua/ros_bridge#2]
@miguelriemoliveira do you know any cloud filtering algorithms that work based on an given angle? The LIDAR sensors from CARLA gives a point cloud with 360 degrees and in order to adapt the setup to the ATLASCAR i need to reduce these point clouds to the field of view of each sensor of the ATLASCAR. The algorithm i am using works with the PCL format and downsamples the point cloud dataset given a leaf size and  a searchpoint.
![Screenshot from 2019-05-18 17-56-34](https://user-images.githubusercontent.com/22821533/57972734-4b7c3f80-7996-11e9-88c2-349bd967e7ae.png)
I tried to increase the leaf size but i can't get the desired results.
Can you help me?

Thanks
Pedro Silva

**Comment by miguelriemoliveira** [comment]
Hi,

You are using a simulator. So what would make the most sense is to limit
the angles on the simulator side.

Don't you have some configuration file in which you can define the minimum
and maximum angles? Are you using a velodyne? Should you not be using 2D
scanners instead?

If you really need to use ROS to limit the angles a-posteriori then I would
recommend that you transform the point cloud back to the original
data acquisition frame, then convert from cartesian coordinates back to
spherical coordinates, then discard points which are not within you desired
angular range.

Hope it helps,
Miguel

*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*
