### ISSUE TITLE
ROS & PCL - The filtered point clouds do not match - issue #4

### ISSUE THREAD

**Issue by SIlvaMFPedro** [lardemua/ros_bridge#4]
@miguelriemoliveira with a theta angle between [0, 2π]:
https://github.com/lardemua/ros_bridge/blob/ad73d05df3e3e066c8d1ea1dd64a3de71e426c6e/carla_ros_pcl_filter/src/PclFilter.cpp#L282
The point clouds should match with each other but instead of filtering the point cloud it is adding points that should not have been there due to the range of the sensor.
This is the cloud from the topic /carla/ego_vehicle/lidar/front/point_cloud:
![Screenshot from 2019-05-23 11-07-15](https://user-images.githubusercontent.com/22821533/58245759-6dd2dc00-7d4d-11e9-8713-a11db12b3d8e.png)
This is the cloud from the topic /carla/ego_vehicle/lidar/front/new_point_cloud:
![Screenshot from 2019-05-23 11-07-51](https://user-images.githubusercontent.com/22821533/58245811-8b07aa80-7d4d-11e9-8c09-504ef197b6bd.png)
And this is the end result:
![Screenshot from 2019-05-23 11-07-34](https://user-images.githubusercontent.com/22821533/58245883-b8ecef00-7d4d-11e9-98a7-20e4a6680113.png)

Can you help me fix this issue?

**Comment by SIlvaMFPedro** [comment]
It is not adding points my bad. It is just filtering the points that are further away from the vehicle which is still strange.
Looking at from a sphere perspective it is almost as if it is only counting the surface layer points and it is disregarding the points in the internal radius.
What i want to do is something similar to this design:
![sphere-with-pyramid](https://user-images.githubusercontent.com/22821533/58247671-1b47ee80-7d52-11e9-9452-11f5ae5714ee.gif)
in which based on an angle theta we can filter the point cloud as pyramid using the surface layer that we have as the base.
Is it possible to achieve this?

**Comment by SIlvaMFPedro** [comment]
@tiagomfmadeira any ideas? xD

**Comment by miguelriemoliveira** [comment]
Hi @SIlvaMFPedro ,

I do not understand the problem very well. Can you say in one sentence what the problem is?

Even from the title of the issue I do not understand: "The filtered point clouds do not match" ... do not match what?

Another thing, you still have strange swaps when copying coordinates 

https://github.com/lardemua/ros_bridge/blob/ad73d05df3e3e066c8d1ea1dd64a3de71e426c6e/carla_ros_pcl_filter/src/PclFilter.cpp#L278

**Comment by SIlvaMFPedro** [comment]
My problem is that the only part that is being filtered is the end portion of the point cloud, every point between the vehicle(that should be the center of the point cloud) and the end section is being disregarded and thus it doesn't show up in RVIZ.
I can't see what is wrong with the way i am copying the coordinates, if there is an error can you tell the proper way to copy the coordinates correctly?

Thank you.

**Comment by miguelriemoliveira** [comment]
Is it solved now?

**Comment by tiagomfmadeira** [comment]
@SIlvaMFPedro I'm guessing the way you're calculating θ isn't actually correct, and therefore the wrong points are being filtered out. Forget that other reference we found, stickto this:
<p><code>r = √(x² + y² + z²)</code></p>
<p><code>θ = arccos (z/r)</code></p>
<p><code>φ = arctan (y/x)</code></p>
<p>where:<p>

    (x, y, z) are the Cartesian coordinates, and
    (r, θ, φ) are the spherical coordinates.

**Comment by SIlvaMFPedro** [comment]
I managed to solve the issue using the φ = arctan (y/x).
I was having some issues with the angle because i was using the c++ atan(y/x) function.
![Screenshot from 2019-05-23 16-01-28](https://user-images.githubusercontent.com/22821533/58264919-9d4a0e80-7d76-11e9-8d64-b6d34448fd33.png)
But i switched to the atan2(y,x) function and  with a φ between [-π/2, π/2] here are the results:
![Screenshot from 2019-05-23 16-13-14](https://user-images.githubusercontent.com/22821533/58265119-00d43c00-7d77-11e9-903c-807c0d9b57d9.png)

**Comment by miguelriemoliveira** [comment]
:+1:

**Comment by SIlvaMFPedro** [comment]
Good evening.
I managed to complete filtering setup for all of the LIDAR sensors and here is the result: 
![Screenshot from 2019-05-23 23-10-42](https://user-images.githubusercontent.com/22821533/58290313-3b5aca80-7db1-11e9-98f7-cfc4cd9fd929.png)

Thank you very much for your help ;)

**Comment by miguelriemoliveira** [comment]
No problem.


*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*
