### ISSUE TITLE
ROS & Template Matching - Drawing 3D bounding boxes - issue #5

### ISSUE THREAD

**Issue by SIlvaMFPedro** [lardemua/ros_bridge#5]
Good afternoon.
I developed a ROS node that implements the Template Matching algorithm on the image sequences obtained from the RGB Camera of the vehicle. The templates objects used in this algorithm are cropped out images/objects from the image sequences leaving a green rectangle on the region of interest from which the object was cropped out.
Using these templates, we can use the template matching algorithm in order to find the template object in the image drawing a red rectangle around the object that matches the template:
![carla_template_matching_02](https://user-images.githubusercontent.com/22821533/58372904-df14b980-7f1c-11e9-9cca-bb997d155422.png)
My issue is that this is a 2D bounding box.
How can i transform this 2D bounding box into a 3D bounding box? Do i use the OpenCV projectPoints function?
My problem is that this function requires a camera matrix,  distance coefficients, a translation matrix and a rotation matrix parameters that i don't know how to get since the dimensions of the template are only defined when you cropp out the object from the image and i don't know the 3D location of the object in the world referential nor the camera referential.

@miguelriemoliveira can you help me with this issue?

The end result should look somewhat like this
![image](https://user-images.githubusercontent.com/22821533/58373152-5ba99700-7f21-11e9-9f01-48d1db828d9d.png)

**Comment by SIlvaMFPedro** [comment]
@tiagomfmadeira suggested using fixed dimensions for the template and saving the intrinsics of the camera that took the image and based on that information calculate the distance in which that object is at.
My problem is that since the object models don't have all the same size it is not appropriate to use fixed dimensions when designing the template.

**Comment by miguelriemoliveira** [comment]
Hello,

I think that you have to define the bbox in a hybrid way:

The width w and the height h of the bbox should be defined using the lidar measurements. 
As for the depth you could use a fixed depth **d** for starters.

```
           +--------------+
          /|                  /|   d
         / |                 / |
        *--+-----------*  |
        |  |                |  |
        |  +-----------+--+     h
        | /                | /
        |/                 |/
        *--------------*
               w

```

So you should find out in the lidar data which points are from the object being tagged in the image. Then you can estimate the w,h and d.

**Comment by SIlvaMFPedro** [comment]
I think i am going to need some help with this.
@miguelriemoliveira are you free on monday?

**Comment by miguelriemoliveira** [comment]
Monday I am not sure. Will you be there? If so I will pass by LAR if I have time, but cannot promise.

**Comment by SIlvaMFPedro** [comment]
Yes i will be by LAR but it doesn't have to be tomorrow.
Do you have any free time during the rest of the week? Maybe we can schedule a meeting?

**Comment by miguelriemoliveira** [comment]
Only Thursday I will have time. Better to find some time to go there today...

**Comment by SIlvaMFPedro** [comment]
Good morning.
I managed to develop some callback functions that read the width, height and depth parameters of the point cloud from each one of the LIDAR sensors.
The width and height parameters are read in the callback function:
https://github.com/lardemua/ros_bridge/blob/9a8cea736a2ea31f1c5878222ab960b645874b5c/carla_ros_template_matching/src/carla_ros_template_matching/carla_ros_lidar_point_projection.py#L91-L100
And the depth parameters are calculated using the pc2.read_points() function:
https://github.com/lardemua/ros_bridge/blob/9a8cea736a2ea31f1c5878222ab960b645874b5c/carla_ros_template_matching/src/carla_ros_template_matching/carla_ros_lidar_point_projection.py#L82-L89
Here are some results:
![image](https://user-images.githubusercontent.com/22821533/58411220-b51ddd00-806b-11e9-9fd9-35bf02764684.png)

My question now is do i have to use the width, height and depth parameters of every sensor or do i just use the width, height and depth parameters from the front LIDAR sensor?

**Comment by miguelriemoliveira** [comment]
I think you are confusing the height and width of a point cloud with the
height and width of a bounding box...
*  Miguel Riem de Oliveira                                             *
email:    mriem@ua.pt    |    m.riem.oliveira@gmail.com
Dep. de Engenharia Mecânica, Universidade de Aveiro
*Campus Universitário de Santiago, 3810-193  Portugal*

**Comment by SIlvaMFPedro** [comment]
> Hello,
> 
> I think that you have to define the bbox in a hybrid way:
> 
> The width w and the height h of the bbox should be defined using the lidar measurements.
> As for the depth you could use a fixed depth **d** for starters.
> 
> ```
>            +--------------+
>           /|                  /|   d
>          / |                 / |
>         *--+-----------*  |
>         |  |                |  |
>         |  +-----------+--+     h
>         | /                | /
>         |/                 |/
>         *--------------*
>                w
> ```
> 
> So you should find out in the lidar data which points are from the object being tagged in the image. Then you can estimate the w,h and d.

You said to use the lidar measurements to determine the width and height of the bounding box so i assumed i needed to use the height and width of the point cloud message from the sensors.

Am i not correct?

**Comment by miguelriemoliveira** [comment]
No. You must find out, from all the points in a point cloud (or laser scan) which of those represent the object in the bbox. Then these points give you an indication of the bbox's width and height.

**Comment by SIlvaMFPedro** [comment]
Ok. But that way i have a problem because i have the template object saved as a 2D image and in order to compare with the point cloud of the LIDAR sensors i need to convert this 2D object to a 3D point cloud. Is there a python code that can help me with this?

**Comment by SIlvaMFPedro** [comment]
I am currently trying to save the points from the template image into a numpy array to see if it works.
After lunch i will test this approach and hopefully comeback to you with some results.
