### ISSUE TITLE
ROS & OpenCV - Camera issues and cv::line function is not working - issue #6

### ISSUE THREAD

**Issue by SIlvaMFPedro** [lardemua/ros_bridge#6]
Good morning.
I seem to be having some camera issues when it comes to the OpenCV window because it just freezes on the very first frame while the pygame window runs normally.
![IMG_20190530_105518](https://user-images.githubusercontent.com/22821533/58626091-d8df5e00-82cb-11e9-863c-58d881cecfa5.jpg)
Besides the cv::line function does not seem to be doing anything:
https://github.com/lardemua/ros_bridge/blob/e216d10905bd803d4e23b8bea47e78c729972356/carla_ros_pcl_opencv/src/PclViewer.cpp#L119-L122
I also get these warning messages from ROS from time to time:
![Screenshot from 2019-05-30 10-52-19](https://user-images.githubusercontent.com/22821533/58626356-881c3500-82cc-11e9-8902-dcdbe26ce914.png)
@miguelriemoliveira can you help me with this issue?
Meanwhile i am going to try to use the other RGB camera and see if i can get some different results.

**Comment by SIlvaMFPedro** [comment]
By the way i tried to see if the error was coming from the waitKey() function:
https://github.com/lardemua/ros_bridge/blob/e216d10905bd803d4e23b8bea47e78c729972356/carla_ros_pcl_opencv/src/PclViewer.cpp#L125-L130
But the key event seems to be working since i get the corresponding ROS Info messages printed in the terminal:
![image](https://user-images.githubusercontent.com/22821533/58626761-74250300-82cd-11e9-8569-686cef90d614.png)

**Comment by SIlvaMFPedro** [comment]
I just realized that the results from the other RGB camera will be the same because the camera model is the same *facepalm*

**Comment by SIlvaMFPedro** [comment]
I corrected the coordinates in the for loop
**https://github.com/lardemua/ros_bridge/blob/9d429f790a9f3f1df9a3cf55af601fa5c5ef156f/carla_ros_pcl_opencv/src/PclViewer.cpp#L178-L195**
but the problem maintains :/

**Comment by miguelriemoliveira** [comment]
> By the way i tried to see if the error was coming from the waitKey() function:
> https://github.com/lardemua/ros_bridge/blob/e216d10905bd803d4e23b8bea47e78c729972356/carla_ros_pcl_opencv/src/PclViewer.cpp#L125-L130
> 
> 
> But the key event seems to be working since i get the corresponding ROS Info messages printed in the terminal each time i press a key in the keyboard:
> ![image](https://user-images.githubusercontent.com/22821533/58626761-74250300-82cd-11e9-8569-686cef90d614.png)

You cannot use cvWaitkey(0) because it blocks. It must be cvWaitkey(20) for example, to display each image 20 milisecs.

**Comment by miguelriemoliveira** [comment]
About the cvline not working, draw  a cvline between two know points (e.g. the top left and the bottom right corner of the image). 

If you see a diagonal line, then the problem could be in the coordinates

**Comment by SIlvaMFPedro** [comment]
Changing the waikey() interval solved the blocking issue and now the cvline function just draws an horizontal line on the image.
![image](https://user-images.githubusercontent.com/22821533/58663481-8716f200-8324-11e9-9362-2d541fb93b38.png)

Is this an issue with the coordinates?
