### ISSUE TITLE
Create new setup configuration for road_visual_perception and road_detection packages - issue

### ISSUE THREAD

**Issue by SIlvaMFPedro** [lardemua/ros_bridge#7]
Good morning.
@tmralmeida @danifpdra can you guys please describe all the sensors you are using in your algorithms as well as their current position in the vehicle so that i can then replicate your setup using the sensor configuration file: 
https://github.com/lardemua/ros_bridge/blob/master/carla_ros_vehicle/config/sensors.json .
With this i can create rosbags files for you guys to test out your algorithms later.
Your help would be much appreciated ;)

Thanks,
Pedro Silva

**Comment by tmralmeida** [comment]
Hi @SIlvaMFPedro,

id : "top_right_camera",
"x": -17.7217972603514, "y": 780.398987989879, "z": 1798.90322883126, "roll":3.08517033374988, "pitch": 0.0114432071771162, "yaw": -1.58683126505267,
"width": 964,
"height": 724


id : "top_left_camera",
"x":300.321464816853, "y": 713.849641574408, "z": 1890.67115420697, "roll":3.09315055757511, "pitch":0.0108160149890114, "yaw": -1.60435715276337,
"width": 964,
"height": 724

Angles are in relation to the "moving_axis" frame, and all the localisation values were obtained through the extrinsic calibration.

**Comment by SIlvaMFPedro** [comment]
Hi @tmralmeida .
In CARLA the sensor localization has to be in relation to the moving axis of the vehicle
![image](https://user-images.githubusercontent.com/22821533/59565672-386c9600-904e-11e9-8834-db9854b27900.png)
Also the camera sensors in CARLA don't have any distortion parameters as seen in this function:
https://github.com/lardemua/ros_bridge/blob/cbbb29ca82cadcb2b4eb7ac347d07247b679cd73/carla_ros_bridge/src/carla_ros_bridge/camera.py#L83-L102
So we might have to run back the extrinsic calibrations.
Are you available tomorrow? I should be by LAR at around 9am tomorrow.

**Comment by tmralmeida** [comment]
@SIlvaMFPedro, the camera info of the function that you are showing, is provided by the intrisic calibration! You can access it in the folder ".ros/camera_info" on the ATLASCAR computer.
However, tomorrow we can talk!

**Comment by SIlvaMFPedro** [comment]
Hello @tmralmeida .
Can you provide me with some image results of your algorithm using real images from the ATLASCAR so i can put them in my thesis document? 
Thanks ;)
